workspace = 1, monitor:$mainMon
workspace = 2, monitor:$mainMon
workspace = 3, monitor:$mainMon
workspace = 4, monitor:$mainMon
workspace = 5, monitor:$mainMon
workspace = 6, monitor:$mainMon
workspace = 7, monitor:$mainMon
workspace = 8, monitor:$mainMon
workspace = 9, monitor:$mainMon
workspace = 10, monitor:$mainMon

workspace = 11, monitor:$rightMon
workspace = 12, monitor:$rightMon
workspace = 13, monitor:$rightMon
workspace = 14, monitor:$rightMon
workspace = 15, monitor:$rightMon
workspace = 16, monitor:$rightMon
workspace = 17, monitor:$rightMon
workspace = 18, monitor:$rightMon
workspace = 19, monitor:$rightMon
workspace = 20, monitor:$rightMon

workspace = 21, monitor:$leftMon
workspace = 22, monitor:$leftMon
workspace = 23, monitor:$leftMon
workspace = 24, monitor:$leftMon
workspace = 25, monitor:$leftMon
workspace = 26, monitor:$leftMon
workspace = 27, monitor:$leftMon
workspace = 28, monitor:$leftMon
workspace = 29, monitor:$leftMon
workspace = 30, monitor:$leftMon
